# Generated by Django 2.2.6 on 2020-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logscope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
