# Generated by Django 2.2.6 on 2020-03-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logscope', '0002_auto_20200305_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='persons',
            field=models.ManyToManyField(to='logscope.Person'),
        ),
        migrations.DeleteModel(
            name='Personitems',
        ),
    ]
