# Generated by Django 2.2.6 on 2019-11-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personitems',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='persons.Person')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item')),
            ],
            options={
                'unique_together': {('person', 'item')},
            },
        ),
    ]
