# Generated by Django 2.2.6 on 2019-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('server', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=17, null=True)),
            ],
        ),
    ]
