# Generated by Django 2.2.6 on 2019-11-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventtypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instant', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.ForeignKey(blank=True, db_column='event_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventtypes.Eventtype')),
            ],
        ),
    ]
