# Generated by Django 2.2.6 on 2019-11-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemtypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=17, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=12, null=True)),
                ('item_type', models.ForeignKey(blank=True, db_column='item_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='itemtypes.Itemtype')),
            ],
        ),
    ]
