# Generated by Django 2.2.6 on 2019-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mac_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
